apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i1ybu2ui1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i1ybu2ui1-go 
  name: i1ybu2ui1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i1ybu2ui1-go 
